import {PGlite} from '@electric-sql/pglite'
import fs from 'node:fs'
import assert from 'node:assert/strict'
const db=new PGlite()
await db.exec(`create role anon; create role authenticated; create role service_role; create schema auth; create table auth.users(id uuid primary key);`)
await db.exec(fs.readFileSync(new URL('../supabase/schema.sql',import.meta.url),'utf8'))
const call=async(id,type,day,transaction='HP1',until=null)=>db.query('select public.apply_hotmart_event($1,$2,$3,$4,$5,$6,$7,$8) as result',[id,type,`2026-10-${day}T12:00:00Z`,'user@example.com','SUB1',transaction,'monthly',until])
const paid=async()=> (await db.query("select transaction from payments where status='paid' and valid_until>'2026-10-20T00:00:00Z'")).rows.map(x=>x.transaction)
assert.equal((await call('1','PURCHASE_APPROVED','09','HP1','2026-11-09T12:00:00Z')).rows[0].result,'applied')
assert.equal((await call('1','PURCHASE_APPROVED','09','HP1','2026-11-09T12:00:00Z')).rows[0].result,'duplicate')
await call('2','PURCHASE_DELAYED','10','HP2');assert.deepEqual(await paid(),['HP1'])
await call('3','SUBSCRIPTION_CANCELLATION','11',null);assert.deepEqual(await paid(),['HP1'])
assert.equal((await db.query('select cancelled from subscriptions')).rows[0].cancelled,true)
await call('4','PURCHASE_REFUNDED','12');assert.deepEqual(await paid(),[])
await call('5','PURCHASE_APPROVED','09','HP1','2026-11-09T12:00:00Z');assert.deepEqual(await paid(),[])
await call('6','PURCHASE_COMPLETE','13','HP1','2026-11-09T12:00:00Z');assert.deepEqual(await paid(),[])
await call('7','PURCHASE_APPROVED','14','HP3','2026-12-09T12:00:00Z');assert.deepEqual(await paid(),['HP3'])
await call('8','PURCHASE_CANCELED','13','HP3');assert.deepEqual(await paid(),['HP3'])
await assert.rejects(call('rollback','PURCHASE_APPROVED','15',null,'2026-12-09T12:00:00Z'))
assert.equal((await db.query("select * from hotmart_events where id='rollback'")).rows.length,0)
assert.equal((await db.query("select transaction from payments where status='paid' and valid_until>'2027-01-01T00:00:00Z'")).rows.length,0)
await db.exec('set role authenticated')
await assert.rejects(db.query('select * from payments'))
await assert.rejects(call('forged','PURCHASE_APPROVED','15','FORGED','2027-12-01T00:00:00Z'))
await db.exec('reset role')
console.log('SQL: schema validado; duplicidade, atraso, cancelamento, reembolso terminal, renovação, evento antigo, rollback, expiração e permissões passaram.')
await db.close()
